#### Train Test Split

##### Import Relevant Libraries

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split


In [2]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
b = np.arange(501,601)

#### Splitting the Data

In [4]:
train_test_split(a)

[array([ 39,   9,  25,  63,  47,  97, 100,   2,  13,  38,  64,  93,  42,
         73,  19,  21,  91,  14,  84,  80,  50,  57,  33,  53,  60,  61,
         58,   3,  31,  78,  32,  74,  49,  41,  22,  36,   6,   4,  45,
         29,  44,  17,  62,  65,  95,  35,  27,  16,  56,  55,  15,  89,
         18,  43,   5,   8,  88,  37,  51,  26,  99,  12,   7,  70,  90,
         77,  46,  40,  52,  34,  68,  79,  23,  20,  76]),
 array([75, 24, 83, 67, 96, 54, 94, 48, 66, 71, 92, 98, 87, 59, 10, 82, 72,
        85, 28, 11, 81, 69, 30,  1, 86])]

In [16]:
a_train, a_test = train_test_split(a, test_size=0.2)

#### Exploring The Results

In [17]:
a_train

array([ 11,  30,  59,  96,  20,  39,  90,  31,  60,  10,  67,  47,  77,
        51,  58,  16,  83,  38,  91,  32,   3,  13,  62,  54,  12,  63,
        40,  94,  28,  26,  23,  76,   6,   1,  93, 100,  74,  97,  66,
        65,  89,  27,  24,  19,  25,  14,  41,  35,  72,  37,  50,  46,
        55,  53,  21,  82,   4,  78,  52,  98,  71,  29,  64,  95,  34,
        85,  15,  79,  68,  61,  22,  48,  81,  42,   7,  17,   8,   2,
        45,  57])

In [18]:
a_test

array([ 5, 92, 43, 75, 69,  9, 84, 88, 86, 33, 44, 18, 73, 87, 36, 80, 56,
       70, 49, 99])